### ISSUE TITLE
Tab-Completions missing when there's both subcommands and arguments

### ISSUE THREAD

**Issue by Valjean42** [EnvyWare/API#37]
I have a command (let's call it `yesno`) with a single subcommand (let's call it `maybe`). `yesno` has an implementation with a single completable argument. When I write `/yesno `, it shows the completable options of `yesno`'s argument, but does not show the `maybe` subcommand as an option, though it does recognize the command when I write it anyway.

**Comment by Valjean42** [comment]
This is in forge16 btw.

**Comment by danorris709** [comment]
I don't remember who asked, or why, but this was an intentional change (0e71524b)

**Comment by Valjean42** [comment]
curious. Well I guess I'll have to do the tab completions for my command manually in that case?

**Comment by Valjean42** [comment]
Would it be possible then to add an optional boolean to the @Completable  annotation which, is defaulted to the current behavior, but allows adding the subcommands to the completion list?

**Comment by danorris709** [comment]
if we were to do something like this putting it in the Completable annotation wouldn't really make much sense, as it's a command level issue rather than an issue at an argument level. It would need to be on the class, or method, itself. Even then I don't really think it's necessary, but I'm not too sure what specifically you're doing to come across this issue

**Comment by Valjean42** [comment]
basically I just have a command that has both a subcommand, and a completable argument. I *can* just make the entire tabcompleter for it custom, and that would show all 3 options, but I prefer not having to do that. I can show you the exact code just not in this public platform, let me know if you want it to understand my point
